name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and publish with Gradle
        run: ./gradlew build publish
        env:
          MODRINTH: ${{ secrets.MODRINTH }}
          CHANGELOG: ${{ github.event.release.body }}
          RELEASE: true
